# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ixcode' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ixcode
platform :ios,'7.0'
pod 'MBProgressHUD', '~> 0.9.2'
platform :ios,'7.0'
pod 'MJExtension', '~> 3.0.8'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'
platform :ios,'7.0'
pod 'SDWebImage', '~> 3.7.4'

  target 'ixcodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
